# Pré-processamento dos Dados do CPGF

**Projeto:** Detecção de Anomalias no Uso do Cartão de Pagamento do Governo Federal  
**Disciplina:** Mineração de Dados  
**Etapa:** 1.Pré-processamento

---

## 0. Configuração do Ambiente

Montagem do ambiente para instalação de dependências e importação das bibliotecas necessárias.

In [1]:
%%capture
!pip install pandas matplotlib seaborn scikit-learn plotly

In [2]:
%%capture
!pip install -r ../requirements.txt

## 1. Carregamento dos Dados

Leitura dos arquivos CSV do CPGF (a partir de 2022) com link disponível na pasta `dados/`.

> O link é um redirecionamento para o Drive com 36 datasets.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob
import warnings
import plotly.express as px
from sklearn.preprocessing import StandardScaler
import numpy as np
from scipy.stats import norm


warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.figsize'] = (12, 6)


print('Bibliotecas carregadas com sucesso.')

Bibliotecas carregadas com sucesso.

In [4]:
csv_files = sorted(glob.glob(os.path.join("../datasets", '*.csv')))
print(f'Arquivos encontrados: {len(csv_files)}')

aux=0
dfs = []

for f in csv_files:
    df_temp = pd.read_csv(f, sep=';', encoding='latin-1', decimal = ',')
    dfs.append(df_temp)
    aux+=1
    if aux <= 3:
        print(f'  - {os.path.basename(f)}')
    elif aux == 3:    
        print("  - ...")

df = pd.concat(dfs, ignore_index=True)

print(f'\nTotal de registros carregados: {df.shape[0]:,}')

print(f'Total de colunas: {df.shape[1]} \n')

print(f'Nomes das Colunas: {df.columns}')

Arquivos encontrados: 36
  - 202201_CPGF.csv
  - 202202_CPGF.csv
  - 202203_CPGF.csv

Total de registros carregados: 411,652
Total de colunas: 15

Nomes das Colunas: Index(['CÓDIGO ÓRGÃO SUPERIOR', 'NOME ÓRGÃO SUPERIOR', 'CÓDIGO ÓRGÃO',
       'NOME ÓRGÃO', 'CÓDIGO UNIDADE GESTORA', 'NOME UNIDADE GESTORA',
       'ANO EXTRATO', 'MÊS EXTRATO', 'CPF PORTADOR', 'NOME PORTADOR',
       'CNPJ OU CPF FAVORECIDO', 'NOME FAVORECIDO', 'TRANSAÇÃO',
       'DATA TRANSAÇÃO', 'VALOR TRANSAÇÃO'],
      dtype='str')

---

## 2. Exploração dos Dados
### 2.1 Fundamentação Teórica

Utilizamos as seguintes técnicas e ferramentas:
- alteramos a coluna VALOR TRANSAÇÃO para float.

- Estatísticas resumidas (média, mediana, desvio padrão, quartis);
- Visualizações gráficas para identificar
  distribuições, padrões e possíveis anomalias visuais nos atributos.

Essa parte foi necessaria antes de aplicar qualquer técnica de mineração

| Campo                     | Descrição resumida |
|---------------------------|--------------------|
| Código Órgão Superior     | Identificador do órgão superior responsável pelo cartão. |
| Nome Órgão Superior       | Nome do órgão superior da unidade gestora. |
| Código Órgão Subordinado  | Identificador do órgão subordinado ao órgão superior. |
| Nome Órgão Subordinado    | Nome do órgão subordinado da unidade gestora. |
| Código Unidade Gestora    | Código da unidade responsável pela gestão do recurso. |
| Nome Unidade Gestora      | Nome da unidade gestora. |
| Ano Extrato               | Ano em que ocorreu a transação. |
| Mês Extrato               | Mês em que ocorreu a transação. |
| CPF Portador              | CPF do portador do cartão que realizou a transação. |
| Nome Portador             | Nome do portador do cartão. |
| Transação                 | Tipo de operação realizada com o cartão (compra, saque, etc.). |
| Data Transação            | Data em que a transação foi efetuada. |
| CNPJ ou CPF do Favorecido | Documento de quem recebeu o pagamento. |
| Nome Favorecido           | Nome do estabelecimento ou pessoa que recebeu o valor. |
| Valor Transação           | Valor monetário da transação realizada. |

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 411652 entries, 0 to 411651
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CÓDIGO ÓRGÃO SUPERIOR   411652 non-null  int64
 1   NOME ÓRGÃO SUPERIOR     411652 non-null  str
 2   CÓDIGO ÓRGÃO            411652 non-null  int64
 3   NOME ÓRGÃO              411652 non-null  str
 4   CÓDIGO UNIDADE GESTORA  411652 non-null  int64
 5   NOME UNIDADE GESTORA    411652 non-null  str
 6   ANO EXTRATO             411652 non-null  int64
 7   MÊS EXTRATO             411652 non-null  int64
 8   CPF PORTADOR            312122 non-null  str
 9   NOME PORTADOR           411652 non-null  str
 10  CNPJ OU CPF FAVORECIDO  411652 non-null  int64
 11  NOME FAVORECIDO         411652 non-null  str
 12  TRANSAÇÃO               411652 non-null  str
 13  DATA TRANSAÇÃO          312122 non-null  str
 14  VALOR TRANSAÇÃO         411652 non-null  float64
dtypes: float64(1), int64(6), str(8)
memory usage: 47.1 MB

In [6]:
df['DATA TRANSAÇÃO'] = pd.to_datetime(df['DATA TRANSAÇÃO'], format='%d/%m/%Y')

In [7]:
df['DATA TRANSAÇÃO'].head()

0   2021-12-08
1   2021-12-01
2   2021-12-16
3   2021-12-06
4   2021-11-25
Name: DATA TRANSAÇÃO, dtype: datetime64[us]

In [8]:
# --- 2.2 Visão geral do DataFrame ---
print(' Primeiras linhas ')
display(df.head())

print('\n Informações gerais')
df.info()

 Primeiras linhas

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
0,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2022,1,***.177.590-**,EDSON LUIS GARCIA FAGUNDES,1368970000107,RANZAN & GRAF LTDA,COMPRA A/V - R$ - APRES,2021-12-08,40.6
1,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2022,1,***.725.752-**,VIVIANE CORREA LIMA,84646934000195,PORTOSOFT COMERCIO DE PRODUTOS DE INFORMATICA ...,COMPRA A/V - R$ - APRES,2021-12-01,225.0
2,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2022,1,***.384.652-**,CARLOS EPAMINONDAS GOMES DA SILVA,5452754000104,KSB ELETRONICA LTDA,COMPRA A/V - R$ - APRES,2021-12-16,589.0
3,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2022,1,***.177.590-**,EDSON LUIS GARCIA FAGUNDES,-2,NAO SE APLICA,SAQUE CASH/ATM BB,2021-12-06,360.0
4,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2022,1,***.177.590-**,EDSON LUIS GARCIA FAGUNDES,-2,NAO SE APLICA,SAQUE CASH/ATM BB,2021-11-25,90.0

 Informações gerais
<class 'pandas.DataFrame'>
RangeIndex: 411652 entries, 0 to 411651
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CÓDIGO ÓRGÃO SUPERIOR   411652 non-null  int64
 1   NOME ÓRGÃO SUPERIOR     411652 non-null  str
 2   CÓDIGO ÓRGÃO            411652 non-null  int64
 3   NOME ÓRGÃO              411652 non-null  str
 4   CÓDIGO UNIDADE GESTORA  411652 non-null  int64
 5   NOME UNIDADE GESTORA    411652 non-null  str
 6   ANO EXTRATO             411652 non-null  int64
 7   MÊS EXTRATO             411652 non-null  int64
 8   CPF PORTADOR            312122 non-null  str
 9   NOME PORTADOR           411652 non-null  str
 10  CNPJ OU CPF FAVORECIDO  411652 non-null  int64
 11  NOME FAVORECIDO         411652 non-null  str
 12  TRANSAÇÃO               411652 non-null  str
 13  DATA TRANSAÇÃO          312122 non-null  datetime64[us]
 14  VALOR TRANSAÇÃO         411652 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(6), str(7)
memory usage: 47.1 MB

In [9]:
# --- 2.3 Estatísticas descritivas ---
print(' Estatísticas descritivas (atributos numéricos) ')
display(df.describe())

print('\n Estatísticas descritivas (atributos categóricos) ')
display(df.describe(include='object'))

 Estatísticas descritivas (atributos numéricos)

,CÓDIGO ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,CÓDIGO UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CNPJ OU CPF FAVORECIDO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
count,411652.000000,411652.000000,411652.000000,411652.000000,411652.000000,4.116520e+05,312122,411652.000000
mean,35787.258318,30911.044040,193672.907524,2023.010757,7.436845,1.456817e+13,2023-06-24 13:20:24.882578,683.603481
min,20000.000000,20101.000000,110001.000000,2022.000000,1.000000,-1.100000e+01,2021-11-16 00:00:00,0.040000
25%,26000.000000,25205.000000,114625.000000,2022.000000,5.000000,-2.000000e+00,2022-09-19 00:00:00,125.000000
50%,30000.000000,26409.000000,160160.000000,2023.000000,8.000000,4.006471e+12,2023-06-22 00:00:00,356.710000
75%,47000.000000,30108.000000,200364.000000,2024.000000,10.000000,2.069923e+13,2024-04-09 00:00:00,1000.000000
max,81000.000000,81000.000000,888310.000000,2024.000000,12.000000,9.874986e+13,2024-11-26 00:00:00,207953.600000
std,11399.429079,10231.341767,116415.455532,0.821223,3.267999,2.231868e+13,NaN,2164.235331

 Estatísticas descritivas (atributos categóricos)

,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO,NOME UNIDADE GESTORA,CPF PORTADOR,NOME PORTADOR,NOME FAVORECIDO,TRANSAÇÃO
count,411652,411652,411652,312122,411652,411652,411652
unique,30,194,1255,9883,9932,60321,8
top,Ministério da Justiça e Segurança Pública,Polícia Federal,COORDENACAO GERAL DE ADMINISTRACAO CGAD/DLOG/,***.735.900-**,Sigiloso,Sigiloso,COMPRA A/V - R$ - APRES
freq,83599,79609,21527,1071,99530,99530,265854

In [10]:
# --- 2.4 Visualizações exploratórias ---

import plotly.express as px
fig = px.violin(df, x="ANO EXTRATO", y="VALOR TRANSAÇÃO", box=True)

fig.update_layout(
    width=1000,
    height=600,
    template="plotly_white",
    xaxis_title="ANO EXTRATO",
    yaxis_title="VALOR TRANSAÇÃO (R$)",
)

fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

---

## 3. Qualidade dos Dados

Os principais problemas tratados nesta etapa são:

#### 3.1 Verificação de Duplicatas
Remoção de registros exatos para evitar enviesamento.

#### 3.2 Análise de Valores Ausentes
Identificação de campos nulos resultantes de falhas ou características de sigilo.

#### 3.3 Tratamento de Valores Específicos (Sigilosos)
Tratamento de dados estruturalmente ocultos (ex: CPF e Datas mascarados).

#### 3.4 Tratamento de Valores Ausentes (Geral)
Imputação de valores estatísticos básicos nas demais colunas.

#### 3.5 Tratamento de Ruído e Inconsistências
Avaliação de valores que podem confundir o algoritmo (ex: negativos).

#### 3.1 Verificação de Duplicatas

Verificação de registros duplicados na base de dados conforme solicitado.

In [ ]:
# --- 3.1 Verificação de duplicatas ---
df[df.duplicated()]
print("Total de linhas:", len(df))
print("Duplicadas:", df.duplicated().sum())
df[df.duplicated(keep=False)].head()

In [ ]:
# --- 3.2 Análise de valores ausentes ---
print('Valores ausentes por coluna')
df.isna().sum()

#### 3.2 (cont.) - Verficação de dados nulos

In [17]:
# Mostra a soma de valores nulos para cada coluna
nulos_por_coluna = df.isnull().sum()
print(nulos_por_coluna[nulos_por_coluna > 0]) # Mostra apenas as colunas que têm nulos

CPF PORTADOR      99530
DATA TRANSAÇÃO    99530
dtype: int64

In [15]:
# Filtra o DataFrame mostrando apenas as linhas que contêm algum valor nulo
linhas_com_nulos = df[df.isnull().any(axis=1)]
display(linhas_com_nulos.head()) # Mostra as 5 primeiras para você dar uma olhada

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
2140,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.0
2141,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.0
2142,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,800.0
2143,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.0
2144,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,980.0

In [18]:
# 1. Criar uma máscara para identificar as linhas sigilosas
# (Podemos usar o NOME PORTADOR ou verificar se o CPF está vazio/nulo)
mask_sigiloso = df['NOME PORTADOR'] == 'Sigiloso'

In [19]:
df_sigiloso = df[mask_sigiloso]
df_sigiloso

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
2140,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2141,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2142,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,800.00
2143,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2144,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,980.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411611,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,2553.21
411612,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,105.00
411613,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,60.00
411614,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,35.00
411615,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,NaN,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,30.00

In [20]:
# 2. Imputar os valores ausentes usando o NOME UNIDADE GESTORA
df.loc[mask_sigiloso, 'CPF PORTADOR'] = 'SIGILOSO - ' + df.loc[mask_sigiloso, 'NOME UNIDADE GESTORA']

In [23]:
df.loc[mask_sigiloso]

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
2140,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2141,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2142,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,800.00
2143,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,1000.00
2144,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,980.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411611,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,2553.21
411612,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,105.00
411613,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,60.00
411614,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,35.00
411615,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,NaT,30.00

In [27]:
df.loc[mask_sigiloso]

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
2140,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2022-01-01,1000.00
2141,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2022-01-01,1000.00
2142,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2022-01-01,800.00
2143,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2022-01-01,1000.00
2144,25000,Ministério da Fazenda,25915,Fundo Constitucional do Distrito Federal,170395,FCDF±SSP ± POLICIA CIVIL DO DF,2022,1,SIGILOSO - FCDF±SSP ± POLICIA CIVIL DO DF,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2022-01-01,980.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411611,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2024-01-12,2553.21
411612,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2024-01-12,105.00
411613,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2024-01-12,60.00
411614,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2024-01-12,35.00
411615,20000,Presidência da República,20101,Presidência da República,110322,GABINETE DE SEGURANCA INSTITUCIONAL/PR,2024,12,SIGILOSO - GABINETE DE SEGURANCA INSTITUCIONAL/PR,Sigiloso,-11,Sigiloso,Informações protegidas por sigilo,2024-01-12,30.00

### 3.3 Tratar data ausente de transações sigilosas 
aqui usamos a estratégia de estimar valores ausentes em vez de ignorar.
ao analisar a estrutura  CSV vimos que mesmo quando a "DATA TRANSAÇÃO" está vazia (""), as colunas "ANO EXTRATO" e "MÊS EXTRATO" continuam preenchidas perfeitamente.
para isso vamos usar a vetorização do pandas para construir essa data agregando o dia "01" com o Mês e Ano já existentes na tabela:

In [24]:
# 2. Garantir que Mês e Ano sejam strings para podermos concatenar
# O zfill(2) garante que o mês '1' fique '01'
mes_str = df.loc[mask_sigiloso, 'MÊS EXTRATO'].astype(str).str.zfill(2)
ano_str = df.loc[mask_sigiloso, 'ANO EXTRATO'].astype(str)

In [25]:
# 3. Imputar a data ausente forçando o dia 01
df.loc[mask_sigiloso, 'DATA TRANSAÇÃO'] = '01/' + mes_str + '/' + ano_str

In [26]:
# 4. Agora você pode converter a coluna inteira para datetime sem que o código quebre!
df['DATA TRANSAÇÃO'] = pd.to_datetime(df['DATA TRANSAÇÃO'], format='%d/%m/%Y')

In [ ]:
# --- 3.4 Tratamento de valores ausentes ---

# Estratégia 1: Eliminar colunas com mais de X% de nulos
LIMIAR_NULOS = 70  # percentual
colunas_excluir = resumo_nulos[resumo_nulos['% do Total'] > LIMIAR_NULOS].index.tolist()
print(f'Colunas removidas (> {LIMIAR_NULOS}% nulos): {colunas_excluir}')
df.drop(columns=colunas_excluir, inplace=True, errors='ignore')

# Estratégia 2: Para colunas numéricas restantes, imputar com mediana
cols_numericas = df.select_dtypes(include=[np.number]).columns
for col in cols_numericas:
    if df[col].isnull().sum() > 0:
        mediana = df[col].median()
        df[col].fillna(mediana, inplace=True)
        print(f'  Coluna "{col}": nulos imputados com mediana = {mediana:.2f}')

# Estratégia 3: Para colunas categóricas, imputar com moda ou 'DESCONHECIDO'
cols_categoricas = df.select_dtypes(include='object').columns
for col in cols_categoricas:
    if df[col].isnull().sum() > 0:
        df[col].fillna('DESCONHECIDO', inplace=True)
        print(f'  Coluna "{col}": nulos preenchidos com "DESCONHECIDO"')

print(f'\nValores ausentes restantes: {df.isnull().sum().sum()}')

In [ ]:
# --- 3.5 Remoção de ruído e dados inconsistentes ---

# TODO: Ajustar conforme as colunas reais do CSV
# Exemplo: remover transações com valor = 0 (sem significado)
# col_valor = 'VALOR_TRANSACAO'
# n_antes = len(df)
# df = df[df[col_valor] != 0]
# print(f'Registros com valor 0 removidos: {n_antes - len(df)}')

# Nota: Valores negativos podem representar estornos legítimos ou erros.
# Avaliar e documentar a decisão:
# n_negativos = (df[col_valor] < 0).sum()
# print(f'Transações com valor negativo: {n_negativos}')
# Decisão: manter valores negativos para análise ou remover como ruído?

print('Etapa de remoção de ruído concluída.')
print(f'Shape atual do DataFrame: {df.shape}')

---

## 4. Agregação dos Dados

### 4.1 Fundamentação

Nesta etapa, criamos um novo dataframe agrupando os dados por CPF do portador do cartão. O objetivo é transformar os dados  em um
perfil de comportamento por portador do cartão, bisando que os algoritmos de mineração identifiquem padrões e anomalias do usuário.

In [ ]:
# --- 4.2 Agregação por CPF do portador ---

df_servidor = (
    df.groupby('CPF PORTADOR')
      .agg(
          total_gasto=('VALOR TRANSAÇÃO', 'sum'),
          media_gasto=('VALOR TRANSAÇÃO', 'mean'),
          qtd_transacoes=('VALOR TRANSAÇÃO', 'count'),
          max_gasto=('VALOR TRANSAÇÃO', 'max')
      )
      .reset_index()
)

In [ ]:
df_servidor.head()

---

## 5. Transformação dos Dados
### 5.1 Normalização

Técnicas comuns de normalização:

- **Min-Max Scaling:** Transforma os valores para o intervalo [0, 1].
- **Z-Score (Standardization):** Centraliza na média 0 e desvio padrão 1.

Utilizaremos StandardScaler (Z-Score) neste projeto, pois é mais robusto
na presença de outliers que a normalização Min-Max.

In [ ]:
from sklearn.preprocessing import StandardScaler

features = ['total_gasto', 'media_gasto', 'qtd_transacoes', 'max_gasto']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_servidor[features])

In [ ]:
df_scaled = pd.DataFrame(
    X_scaled,
    columns=features,
    index=df_servidor.index
)

In [ ]:
df_scaled.head()

---

## 6. Exportação dos Dados Pré-processados

O DataFrame limpo e normalizado é salvo para ser consumido pelo Notebook 02 (Mineração).

In [ ]:
# --- 6.1 Salvar dados processados ---
OUTPUT_DIR = os.path.join('..', 'dados')
# Para Colab:
# OUTPUT_DIR = '/content/drive/MyDrive/cpgf-anomaly-detection/dados'

# DataFrame original limpo (sem normalização) — para análise qualitativa no Notebook 03
df.to_csv(os.path.join(OUTPUT_DIR, 'cpgf_limpo.csv'), index=False, sep=';', encoding='utf-8')
print('Arquivo salvo: cpgf_limpo.csv')

# DataFrame normalizado — para entrada nos algoritmos de agrupamento
df_normalizado.to_csv(os.path.join(OUTPUT_DIR, 'cpgf_normalizado.csv'), index=False, sep=';', encoding='utf-8')
print('Arquivo salvo: cpgf_normalizado.csv')

print(f'\nShape final: {df_normalizado.shape}')
print('\n✅ Pré-processamento concluído com sucesso!')